tx = input('Digite algo: ')
print('o tipo primitivo desse valor é ',type(tx))
print('so tem espaços? ',tx.isspace())
print('é um numero? ',tx.isnumeric())
print('é alfabetico? ',tx.isalpha())
print('è alfanumerico? ',tx.isalnum())
print('é maiscula? ',tx.isupper())
print('é minuscula? ',tx.islower())
print('esta capitalizada? ',tx.istitle())
